###########################################
# Role + RoleBinding (namespace-scoped)
###########################################
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-pod-reader
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch" ]