apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-pod-reader-binding
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: prometheus-pod-reader
  apiGroup: rbac.authorization.k8s.io