apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: browser-service-registry
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: browser-service-registry
spec:
  source:
    type: Binary
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jdk17-slim:latest
  output:
    to:
      kind: ImageStreamTag
      name: browser-service-registry:latest
---