cdp:
  ws:
    host: localhost
registry:
  host: http://localhost:8081/api/v1
ip:
  address: ${POD_IP:127.0.0.1}
#logging:
#  level:
#    root: debug
# ws://host:9223/session/{sessionId}/devtools/browser/<browser-uuid>