server:
  port: 8080
spring:
  application:
    name: browser-service
  main:
    web-application-type: reactive
  websocket:
    compression:
      enabled: false
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,liveness   # expose actuator endpoints
  metrics:
    export:
      prometheus:
        enabled: true                     # enable Prometheus registry
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessstate:
      enabled: true
browser:
  mode: true
registry:
  host: http://browser-service-registry/api/v1
ip:
  address: ${POD_IP:127.0.0.1}

#logging:
#  level:
#    root: debug
# ws://host:9223/session/{sessionId}/devtools/browser/<browser-uuid>