spring:
  application:
    name: browser-service
  main:
    web-application-type: reactive
  websocket:
    compression:
      enabled: false
server:
  port: 8080

cdp:
  ws:
    host: localhost

#logging:
#  level:
#    root: debug
# ws://host:9223/session/{sessionId}/devtools/browser/<browser-uuid>